version: '3'

services:
  app:
    image: alpine-rvm
    build:
      context: .
      args:
        BUNDLER_VERSION: # Add this detail. for example: 1.16.0
        RUBYGEMS_VERSION: # Add this detail. for example: 2.6.12
        RUBY_VERSION: # Add this detail. for example: ruby-2.3.4
        RUBY_GEMSET: # Add this detail. for example: routing-manager
        PASSENGER_APP_ENV: # Add this detail. for example: development
    ports:
      - "3000:80"
    healthcheck:
          test: [ 'CMD-SHELL', '/usr/bin/curl -q -s --fail -H "X-Forwarded-For: health.docker.localdomain" http://localhost:80' ]
          interval: 30s
          timeout: 10s
          retries: 3
    tty: true
