version: '3'

services:
  app:
    image: myruby-project
    build:
      context: .
      args:
        BUNDLER_VERSION: 1.16.0
        RUBYGEMS_VERSION: 2.6.12
        RUBY_VERSION: ruby-2.3.4
        RUBY_GEMSET: mygemset
        PASSENGER_APP_ENV: development
    ports:
      - "3000:80"
    healthcheck:
          test: [ 'CMD-SHELL', '/usr/bin/curl -q -s --fail -H "X-Forwarded-For: health.docker.localdomain" http://localhost:80' ]
          interval: 30s
          timeout: 10s
          retries: 3
    tty: true
